#!/usr/bin/env python3
"""Reconcile deterministic governance views from canonical project records."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


CARD_RE = re.compile(r"^## (V1-C(?:0[1-9]|1[0-9]|20)) — (.+)$")
BEGIN = "<!-- BEGIN GENERATED: {name} -->"
END = "<!-- END GENERATED: {name} -->"
NOTICE = "DO NOT EDIT THIS BLOCK MANUALLY. Generated by scripts/reconcile_governance_views.py."


def section(text: str, heading: str) -> str:
    """Return one exact level-2 section, including its heading."""
    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if line == heading), None)
    if start is None:
        raise ValueError(f"missing section: {heading}")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    return "\n".join(lines[start:end])


def subsection(text: str, heading: str) -> str:
    """Return one exact level-3 subsection from an isolated Card section."""
    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if line == heading), None)
    if start is None:
        raise ValueError(f"missing subsection: {heading}")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("### ")), len(lines))
    return "\n".join(lines[start:end])


def value_after_heading(text: str, heading: str) -> str:
    lines = subsection(text, heading).splitlines()[1:]
    values = [line.strip() for line in lines if line.strip() and not line.strip().startswith("#")]
    return values[0] if values else ""


def evidence_value(card_section: str, heading: str) -> str:
    return value_after_heading(card_section, heading)


def evidence_state(card_section: str) -> str:
    return evidence_value(card_section, "### 3. State").split(" —", 1)[0]


def evidence_tests(card_section: str) -> str:
    value = evidence_value(card_section, "### 7. Focused Tests")
    return "PASS" if value.startswith("PASS") else "NOT_RUN" if value.startswith("NOT_RUN") else value.split()[0]


def evidence_exit(card_section: str) -> str:
    subsection_text = subsection(card_section, "### 14. Exit Gate Evidence")
    match = re.search(r"^Exit Gate Status:\s*(\S+)", subsection_text, re.MULTILINE)
    return match.group(1) if match else "NOT_PROVEN"


def evidence_learning(card_section: str) -> str:
    value = evidence_value(card_section, "Learning Documentation Status:") if "Learning Documentation Status:" in card_section else ""
    return value


def evidence_presence(card_section: str) -> str:
    value = evidence_value(card_section, "### 5. Files Changed")
    return "NONE" if value in {"NONE", "NOT_OBSERVED", "NOT_OBSERVED_FOR_THIS_CARD"} else "PRESENT"


def parse_cards(roadmap: str) -> list[tuple[str, str]]:
    cards = [match.groups() for match in map(CARD_RE.match, roadmap.splitlines()) if match]
    if not cards:
        raise ValueError("no V1 Card headings found in Roadmap")
    return cards


def parse_control_rows(control: str) -> dict[str, dict[str, str]]:
    rows: dict[str, dict[str, str]] = {}
    table_start = control.find("## 18. V1 Card Status Table")
    if table_start < 0:
        raise ValueError("missing PROJECT_CONTROL V1 Card Status Table")
    table = control[table_start:]
    for line in table.splitlines():
        if not line.startswith("| V1-C"):
            continue
        fields = [field.strip() for field in line.strip("|").split("|")]
        if len(fields) != 6:
            raise ValueError(f"invalid PROJECT_CONTROL Card row: {line}")
        card, title, state, approval, quality, evidence = fields
        rows[card] = {"title": title, "state": state, "approval": approval, "quality": quality, "evidence": evidence}
    return rows


def control_field(control: str, label: str) -> str:
    match = re.search(rf"^{re.escape(label)}\s*(.*)$", section(control, "## 2. Current Project State"), re.MULTILINE)
    if not match:
        raise ValueError(f"missing PROJECT_CONTROL field: {label}")
    return match.group(1).strip()


def parse_active(control: str) -> str:
    value = control_field(control, "Active Card:")
    value = value.split(" —", 1)[0].strip()
    return "" if value == "NONE" else value


def parse_completed(control: str) -> list[str]:
    roadmap_section = section(control, "## 7. Roadmap Position")
    match = re.search(r"^Completed Cards:\s*(.*)$", roadmap_section, re.MULTILINE)
    if not match:
        raise ValueError("missing completed-card field")
    return re.findall(r"V1-C\d{2}", match.group(1))


def card_evidence_sections(evidence: str) -> dict[str, str]:
    matches = list(re.finditer(r"^## (V1-C(?:0[1-9]|1[0-9]|20)) — .+$", evidence, re.MULTILINE))
    result: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(evidence)
        result[match.group(1)] = evidence[match.start():end]
    return result


def generated_view_data(root: Path) -> tuple[list[tuple[str, str, dict[str, str], str]], str]:
    roadmap = (root / "AI_QUOTATION_INTELLIGENCE_V1_ROADMAP.md").read_text()
    control = (root / "PROJECT_CONTROL.md").read_text()
    evidence_text = (root / "QUOTATION_CARD_EVIDENCE_MAP.md").read_text()
    cards = parse_cards(roadmap)
    control_rows = parse_control_rows(control)
    evidence_sections = card_evidence_sections(evidence_text)
    active = parse_active(control)
    completed = parse_completed(control)

    if active and active not in dict(cards):
        raise ValueError(f"Active Card is not in Roadmap: {active}")
    for card, title in cards:
        if card not in control_rows:
            raise ValueError(f"Card missing from PROJECT_CONTROL status table: {card}")
        if card not in evidence_sections:
            raise ValueError(f"Card missing from Evidence Map: {card}")
        if control_rows[card]["title"] != title:
            raise ValueError(f"Card title mismatch for {card}")
        evidence_title = next((line for line in evidence_sections[card].splitlines() if line == f"{card} — {title}"), None)
        if evidence_title is None:
            raise ValueError(f"Card title mismatch in Evidence Map: {card}")
    if active and control_rows[active]["state"] not in {"ACTIVE", "READY_FOR_DELIVERY"}:
        raise ValueError(f"Active Card has incompatible lifecycle state: {active}")
    if active and active not in completed and control_rows[active]["state"] == "COMPLETE":
        raise ValueError(f"completed Active Card is not in Completed Cards: {active}")

    rows = []
    for card, title in cards:
        control_row = control_rows[card]
        evidence_section = evidence_sections[card]
        rows.append((card, title, control_row, evidence_section))

    card_indexes = {card: index for index, (card, _) in enumerate(cards)}
    next_card = "NONE"
    if active in dict(cards):
        active_index = [card for card, _ in cards].index(active)
        if active_index + 1 < len(cards):
            next_card = cards[active_index + 1][0]
    elif completed:
        completed_indexes = [card_indexes[card] for card in completed if card in card_indexes]
        if completed_indexes and max(completed_indexes) + 1 < len(cards):
            next_card = cards[max(completed_indexes) + 1][0]
    elif cards:
        next_card = cards[0][0]
    summary_lines = ["Project Phase: " + control_field(control, "Project Phase:")]
    for card, _ in cards:
        if card in completed:
            summary_lines.append(f"{card}: {control_rows[card]['state']}")
        elif card == active:
            summary_lines.append(f"{card}: {control_rows[card]['state']}")
        elif card == next_card:
            summary_lines.append(f"{card}: NOT_AUTHORIZED / {control_rows[card]['state']}")
    summary_lines.extend(
        [
            f"Active Card: {active}" if active else "Active Card: NONE",
            "Completed Cards: " + (", ".join(completed) if completed else "NONE"),
            "No later Card is authorized.",
            "Detailed technical evidence remains in the exact Card sections above; this summary is derived and non-authoritative.",
        ]
    )
    return rows, "\n".join(summary_lines)


def generated_table(root: Path) -> str:
    rows, _ = generated_view_data(root)
    lines = [
        NOTICE,
        "| Card | Title | State | Start Approved | Focused Tests | Exit Gate | Quality Gate | Evidence | Recommended State |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for card, title, control_row, evidence_section in rows:
        recommendation = evidence_value(evidence_section, "### 20. Recommended State")
        lines.append(
            f"| {card} | {title} | {control_row['state']} | {control_row['approval']} | "
            f"{evidence_tests(evidence_section)} | {evidence_exit(evidence_section)} | {control_row['quality']} | "
            f"{evidence_presence(evidence_section)} | {recommendation} |"
        )
    return "\n".join(lines)


def generated_summary(root: Path) -> str:
    _, summary = generated_view_data(root)
    return NOTICE + "\n" + summary


def replace_block(text: str, name: str, content: str) -> tuple[str, bool]:
    begin, end = BEGIN.format(name=name), END.format(name=name)
    replacement = f"{begin}\n{content}\n{end}"
    pattern = re.compile(re.escape(begin) + r"\n.*?\n" + re.escape(end), re.DOTALL)
    if pattern.search(text):
        updated = pattern.sub(replacement, text, count=1)
        return updated, updated != text

    heading = "## 17. Current Card Table" if name == "CURRENT_CARD_TABLE" else "## 18. Current Summary"
    start = text.find(heading)
    if start < 0:
        raise ValueError(f"missing derived section for {name}")
    body_start = text.find("\n", start) + 1
    next_heading = text.find("\n## ", body_start)
    end_position = next_heading if next_heading >= 0 else len(text)
    replacement_section = "\n" + replacement + "\n"
    updated = text[:body_start] + replacement_section + text[end_position:]
    return updated, updated != text


def reconcile(root: Path, write: bool) -> int:
    evidence_path = root / "QUOTATION_CARD_EVIDENCE_MAP.md"
    original = evidence_path.read_text()
    try:
        table = generated_table(root)
        summary = generated_summary(root)
        updated, table_changed = replace_block(original, "CURRENT_CARD_TABLE", table)
        updated, summary_changed = replace_block(updated, "CURRENT_SUMMARY", summary)
    except (OSError, ValueError) as error:
        print(f"GOVERNANCE_VIEW_RECONCILIATION_GATE: FAIL\n{error}\nGOVERNANCE_RECONCILIATION_REQUIRED\nSTOP")
        return 1

    if write and (table_changed or summary_changed):
        evidence_path.write_text(updated)
        try:
            verify = generated_table(root)
            verify_summary = generated_summary(root)
            checked, _ = replace_block(updated, "CURRENT_CARD_TABLE", verify)
            checked, _ = replace_block(checked, "CURRENT_SUMMARY", verify_summary)
            if checked != updated:
                raise ValueError("generated view verification changed after write")
        except (OSError, ValueError) as error:
            print(f"GOVERNANCE_VIEW_RECONCILIATION_GATE: FAIL\n{error}\nGOVERNANCE_RECONCILIATION_REQUIRED\nSTOP")
            return 1
        print("GOVERNANCE_VIEW_RECONCILIATION_GATE: PASS")
        return 0

    if table_changed or summary_changed:
        print("GOVERNANCE_VIEW_RECONCILIATION_GATE: FAIL\nGOVERNANCE_RECONCILIATION_REQUIRED\nSTOP")
        return 1
    print("GOVERNANCE_VIEW_RECONCILIATION_GATE: PASS")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    return reconcile(args.root.resolve(), write=args.write)


if __name__ == "__main__":
    sys.exit(main())
